# مروری بر کتابخانه نامپای

In [15]:
# تشکیل آرایه ای از اعداد
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
my_array=np.array([1,2,3])
print(my_array)

[1 2 3]


In [12]:
print(type(my_array))

<class 'numpy.ndarray'>


In [14]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
#0-D Arrays

a=np.array(42)
print(a)

42


In [17]:
# 1-D Arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [18]:
# 2-D array
# تشکیل آرایه دو بعدی
# یعنی هم سطر داریم و هم ستون

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [19]:
#3-D arrays
# آرایه ای که خود شامل آرایه های دو بعدی میباشد
# به آن ماتریکس هم میگویند

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [20]:
# مشخص کردن ابعاد ارایه
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# دسترسی به المانها آرایه

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [23]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
print( arr[0, 4])
print( arr[1, 1])

5
7


In [34]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [35]:
print(arr[0, 1, 2])

6


In [37]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
print( arr[1, -1])

10


# Slicing arrays

### [start:end:step].

In [39]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [40]:
print(arr[1:])

[2 3 4 5 6 7]


In [41]:
print(arr[:])

[1 2 3 4 5 6 7]


In [42]:
print(arr[:-1])

[1 2 3 4 5 6]


In [43]:
print(arr[-3:-1])

[5 6]


### step

In [45]:
print(arr[0:7:2])


[1 3 5 7]


In [46]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [47]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [48]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [50]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]



# Data Types in Python

strings - used to text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3


float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

# NumPy Data Types
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )


In [52]:
#Checking the Data Type of an Array

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [54]:
#Get the data type of an array containing strings:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [55]:
#Creating Arrays With a Defined Data Type
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


for more information:
    https://www.w3schools.com/python/numpy/numpy_data_types.asp

# The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.



In [56]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [58]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


# Get the Shape of an Array


In [59]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)
